In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Datos experimentales
x_list=[1.3,1.6,1.9]
y_list=[0.6200860,0.4554022,0.2818186]
dydx_list=[-0.5220232,-0.5698959,-0.5811571]

def DiferenciaDividida(x_list,y_list):
    n=len(x_list)
    # Creando lista z
    z=np.zeros(2*n)
    
    #Llenando lista Z
    for i in range(0,n):
        z[2*i]=x_list[i]
        z[2*i+1]=z[2*i]
    
    #Creando matriz de ceros
    a=np.zeros((2*n,2*n))
    
    #Llenando elementos de la diagonal
    for i in range(0,2*n):
        for j in range(0,2*n):
            if i==j:
                a[i][j] = y_list[int(i/2)]

    for k in range(1,2*n):
        for i in range(0,2*n-1): # Limite superior evita la diagnoal
            for j in range(1,2*n): # Limite inferior evita la diagnoal
                if j!=i and j==i+k and z[j]!=z[i]:
                    a[i][j]=(a[i+1][j]-a[i][j-1])/(z[j]-z[i])
                elif j!=i and j==i+k and z[j]==z[i]:
                    a[i][j]=dydx_list[int(i/2)]

    return a

print(DiferenciaDividida(x_list,y_list))

[[ 0.620086   -0.5220232  -0.08974267  0.06636556  0.00266667 -0.00277469]
 [ 0.          0.620086   -0.548946   -0.069833    0.06796556  0.00100185]
 [ 0.          0.          0.4554022  -0.5698959  -0.02905367  0.06856667]
 [ 0.          0.          0.          0.4554022  -0.578612   -0.00848367]
 [ 0.          0.          0.          0.          0.2818186  -0.5811571 ]
 [ 0.          0.          0.          0.          0.          0.2818186 ]]


# Como función 

In [3]:
# Datos experimentales
x_list=[1.0,1.3,1.6,1.9,2.2]
y_list=[0.7651977,0.6200860,0.4554022,0.2818186,0.1103623]


def DiferenciaDividida(x_list,y_list):
    n=len(x_list)
    # Creando matriz de ceros
    a=np.zeros((n,n))
    # Llenando elementos de la diagonal
    for i in range(0,n):
        for j in range(0,n):
            if i==j:
                a[i][j] = y_list[i]
    for k in range(1,n):
        for i in range(0,n-1): # Limite superior evita la diagnoal
            for j in range(1,n): # Limite inferior evita la diagnoal
                if j!=i and j==i+k:
                    a[i][j]=(a[i+1][j]-a[i][j-1])/(x_list[j]-x_list[i])
    return a


